name: Nightly build develop & runner docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['develop', 'server', 'runner']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          target: ${{ matrix.tag }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.tag }}:latest
